// Valeurs par défaut du contenu éditorial (anciennement dans lib/cms/db.ts).
// Les fichiers content/pricing.json et content/seo.json les complètent ou les remplacent.
import type { PricingContent, SeoContent } from "@/lib/cms/types";
import { SITE_URL } from "@/lib/site-url";

export const DEFAULT_PRICING: PricingContent = {
  learningos: [
    {
      name: "Starter",
      description: "Pour structurer rapidement une academie interne pilotee par IA.",
      monthlyPrice: null,
      yearlyPrice: null,
      originalPrice: null,
      setupFee: null,
      cta: "Sur devis",
      ctaLink: "/contact",
      gradient: "var(--module-grad-2)",
      previousPlan: null,
      features: [
        "Generation automatique de parcours de formation personnalises",
        "Adaptation des contenus selon vos metiers et référentiels internes",
        "Agents IA conversationnels pour accompagner les collaborateurs",
        "Suivi des compétences et progression en temps reel",
        "Espace entreprise securise",
        "Deploiement rapide sans équipe pédagogique interne",
        "Compatible financement OPCO",
      ],
      creditLimit: "Sur devis",
      popular: false,
    },
    {
      name: "Growth",
      description: "Pour industrialiser la montée en compétences a l'echelle d'une équipe ou d'un reseau.",
      monthlyPrice: null,
      yearlyPrice: null,
      originalPrice: null,
      setupFee: null,
      cta: "Sur devis",
      ctaLink: "/contact",
      gradient: "var(--module-grad-3)",
      previousPlan: null,
      features: [
        "Tout Starter",
        "Generation avancee de parcours adaptatifs",
        "Adaptation automatique selon les postes, niveaux et objectifs",
        "Bibliotheque metier dynamique alimentee par IA",
        "Tableaux de pilotage RH et compétences",
        "Workflows de validation manageriale",
        "Reporting conformité et tracabilite formation",
        "Assistance au montage des financements publics et OPCO",
        "API et integrations SIRH",
      ],
      creditLimit: "Sur devis",
      popular: false,
    },
    {
      name: "Enterprise",
      description: "Pour construire une veritable infrastructure de formation autonome et adaptative.",
      monthlyPrice: null,
      yearlyPrice: null,
      originalPrice: null,
      setupFee: null,
      cta: "Sur devis",
      ctaLink: "/contact",
      gradient: "var(--module-grad-4)",
      previousPlan: null,
      features: [
        "Tout Growth",
        "Generateur de badges et référentiels internes",
        "Modele pédagogique proprietaire adapte a vos metiers",
        "Ingenierie pédagogique dédiée et accompagnement continu",
        "Integrations avancees SIRH, LMS, CRM",
        "Deploiement multi-sites et multi-pays",
        "SLA garanti et support prioritaire",
        "Conformite RGPD, ISO 27001, accessibilite",
        "Audit Qualiopi et accompagnement conformite",
      ],
      creditLimit: "Sur devis",
      popular: false,
    },
  ],
  pipelineos: [
    {
      name: "Starter",
      description: "ATS, pipeline candidats, matching simple, dashboard RH, workflows recrutement, automatisations basiques.",
      monthlyPrice: null,
      yearlyPrice: null,
      originalPrice: null,
      setupFee: null,
      cta: "Sur devis",
      ctaLink: "/contact",
      gradient: "var(--module-grad-2)",
      previousPlan: null,
      features: [
        "ATS complet",
        "Pipeline candidats",
        "Matching simple",
        "Dashboard RH",
        "Workflows recrutement",
        "Automatisations basiques",
      ],
      creditLimit: "Sur devis",
      popular: false,
    },
    {
      name: "Growth",
      description: "IA matching, scoring, multi-recruteurs, portail candidats, automatisations avancees, analytics RH, onboarding sync MentivisOS Pro.",
      monthlyPrice: null,
      yearlyPrice: null,
      originalPrice: null,
      setupFee: null,
      cta: "Sur devis",
      ctaLink: "/contact",
      gradient: "var(--module-grad-3)",
      previousPlan: null,
      features: [
        "IA matching avance",
        "Scoring candidats",
        "Multi-recruteurs",
        "Portail candidats",
        "Automatisations avancees",
        "Analytics RH",
        "Onboarding sync MentivisOS Pro",
      ],
      creditLimit: "Sur devis",
      popular: false,
    },
    {
      name: "Enterprise",
      description: "Orchestration recrutement, copilots RH, workflows IA, API RH, integration SI RH, multi-filiales, gouvernance, architecture dédiée.",
      monthlyPrice: null,
      yearlyPrice: null,
      originalPrice: null,
      setupFee: null,
      cta: "Sur devis",
      ctaLink: "/contact",
      gradient: "var(--module-grad-5)",
      previousPlan: null,
      features: [
        "Orchestration recrutement",
        "Copilots RH",
        "Workflows IA",
        "API RH complete",
        "Integration SI RH",
        "Multi-filiales",
        "Gouvernance",
        "Architecture dédiée",
      ],
      creditLimit: "Sur devis",
      popular: false,
    },
  ],
  api: [
    {
      name: "Build",
      description: "500k requetes, auth, workflows, embeddings, analytics basiques, rate limiting. Usage IA en supplement.",
      monthlyPrice: null,
      yearlyPrice: null,
      originalPrice: null,
      setupFee: null,
      cta: "Sur devis",
      ctaLink: "/contact",
      gradient: "var(--integration-grad-1)",
      previousPlan: null,
      features: [
        "500k requetes/mois",
        "Authentification",
        "Workflows",
        "Embeddings",
        "Analytics basiques",
        "Rate limiting",
        "Usage IA payant",
      ],
      creditLimit: "Sur devis",
      popular: false,
    },
    {
      name: "Scale",
      description: "5M requetes, orchestration agents, webhooks, multi-workspaces, monitoring, observabilite, support prioritaire. Usage IA en supplement.",
      monthlyPrice: null,
      yearlyPrice: null,
      originalPrice: null,
      setupFee: null,
      cta: "Sur devis",
      ctaLink: "/contact",
      gradient: "var(--integration-grad-2)",
      previousPlan: null,
      features: [
        "5M requetes/mois",
        "Orchestration agents",
        "Webhooks",
        "Multi-workspaces",
        "Monitoring",
        "Observabilite",
        "Support prioritaire",
        "Usage IA payant",
      ],
      creditLimit: "Sur devis",
      popular: false,
    },
    {
      name: "Enterprise",
      description: "Infrastructure dédiée, SLA, private deployment, orchestration IA, gouvernance, conformité, audit logs, acces avance API.",
      monthlyPrice: null,
      yearlyPrice: null,
      originalPrice: null,
      setupFee: null,
      cta: "Sur devis",
      ctaLink: "/contact",
      gradient: "var(--integration-grad-3)",
      previousPlan: null,
      features: [
        "Infrastructure dédiée",
        "SLA garanti",
        "Private deployment",
        "Orchestration IA",
        "Gouvernance",
        "Conformite",
        "Audit logs",
        "Acces avance API",
      ],
      creditLimit: "Sur devis",
      popular: false,
    },
  ],
};

export const DEFAULT_PRICING_EN: PricingContent = {
  learningos: [
    {
      name: "Open MentivisOS",
      description: "Free access to knowledge. Learn what you want, when you want, forever.",
      monthlyPrice: 0, yearlyPrice: 0, originalPrice: 990, setupFee: 0,
      cta: "Free forever!",
      ctaLink: "https://open.mentivisOS.com",
      gradient: "var(--module-grad-2)",
      previousPlan: null,
      features: [
        "Auto-generated personalized training paths",
        "Content adaptation based on your roles and frameworks",
        "Conversational AI agents for employee support",
        "Real-time skills and progress tracking",
        "Up to 4 courses",
        "Learn any subject",
        "Ideal for students as well",
      ],
      creditLimit: "One person",
      popular: true,
    },
    {
      name: "Enterprise Demo",
      description: "Scale up skills training across your team or network.",
      monthlyPrice: 0, yearlyPrice: 0, originalPrice: 2900, setupFee: 0,
      cta: "Test with your programs!",
      ctaLink: "https://demo.mentivisos.com",
      gradient: "var(--module-grad-3)",
      previousPlan: "Starter",
      features: [
        "All Open MentivisOS features",
        "Advanced adaptive program generation",
        "Automatic adaptation by role, level and objective",
        "AI-powered dynamic business library",
        "HR and skills dashboards",
        "Managerial validation workflows",
        "Compliance reporting and training traceability",
        "Public funding and OPCO application assistance",
        "API and HRIS integrations",
      ],
      creditLimit: "500 users",
      popular: false,
    },
    {
      name: "Enterprise",
      description: "Build a truly autonomous and certifying training infrastructure.",
      monthlyPrice: null, yearlyPrice: null, originalPrice: null, setupFee: 15000,
      cta: "Contact the team",
      ctaLink: "/contact",
      gradient: "var(--module-grad-4)",
      previousPlan: "Growth",
      features: [
        "All Growth features",
        "Certification and internal framework generator",
        "Proprietary pedagogical model adapted to your roles",
        "Dedicated pedagogical engineering and ongoing support",
        "Advanced HRIS, LMS, CRM integrations",
        "Multi-site and multi-country deployment",
        "Guaranteed SLA and priority support",
        "GDPR, ISO 27001, accessibility compliance",
        "Qualiopi audit and compliance support",
      ],
      creditLimit: "Unlimited",
      popular: false,
    },
  ],
  pipelineos: [
    {
      name: "Starter",
      description: "ATS, candidate pipeline, basic matching, HR dashboard, recruitment workflows, basic automations.",
      monthlyPrice: null, yearlyPrice: null, originalPrice: 1490, setupFee: null,
      cta: "Choose Starter",
      ctaLink: "https://app.mentivisOS.com",
      gradient: "var(--module-grad-2)",
      previousPlan: null,
      features: [
        "Complete ATS",
        "Candidate pipeline",
        "Basic matching",
        "HR dashboard",
        "Recruitment workflows",
        "Basic automations",
      ],
      creditLimit: "Unlimited",
      popular: false,
    },
    {
      name: "Growth",
      description: "AI matching, scoring, multi-recruiter, candidate portal, advanced automations, HR analytics, MentivisOS Pro onboarding sync.",
      monthlyPrice: null, yearlyPrice: null, originalPrice: 4900, setupFee: null,
      cta: "Choose Growth",
      ctaLink: "/demo",
      gradient: "var(--module-grad-3)",
      previousPlan: "Starter",
      features: [
        "Advanced AI matching",
        "Candidate scoring",
        "Multi-recruiter",
        "Candidate portal",
        "Advanced automations",
        "HR analytics",
        "MentivisOS Pro onboarding sync",
      ],
      creditLimit: "Unlimited",
      popular: true,
    },
    {
      name: "Enterprise",
      description: "Recruitment orchestration, HR copilots, AI workflows, complete HR API, HRIS integration, multi-subsidiary, governance, dedicated architecture.",
      monthlyPrice: null, yearlyPrice: null, originalPrice: null, setupFee: null,
      cta: "Contact the team",
      ctaLink: "/contact",
      gradient: "var(--module-grad-5)",
      previousPlan: "Growth",
      features: [
        "Recruitment orchestration",
        "HR copilots",
        "AI workflows",
        "Complete HR API",
        "HRIS integration",
        "Multi-subsidiary",
        "Governance",
        "Dedicated architecture",
      ],
      creditLimit: "Unlimited",
      popular: false,
    },
  ],
  api: [
    {
      name: "Build",
      description: "500k requests, auth, workflows, embeddings, basic analytics, rate limiting. AI usage billed separately.",
      monthlyPrice: null, yearlyPrice: null, originalPrice: 990, setupFee: null,
      cta: "Get started",
      ctaLink: "https://app.mentivisOS.com",
      gradient: "var(--integration-grad-1)",
      previousPlan: null,
      features: [
        "500k requests/month",
        "Authentication",
        "Workflows",
        "Embeddings",
        "Basic analytics",
        "Rate limiting",
        "Pay-as-you-go AI usage",
      ],
      creditLimit: "500k requests",
      popular: false,
    },
    {
      name: "Scale",
      description: "5M requests, agent orchestration, webhooks, multi-workspaces, monitoring, observability, priority support. AI usage billed separately.",
      monthlyPrice: null, yearlyPrice: null, originalPrice: 3900, setupFee: null,
      cta: "Choose Scale",
      ctaLink: "https://app.mentivisOS.com",
      gradient: "var(--integration-grad-2)",
      previousPlan: "Build",
      features: [
        "5M requests/month",
        "Agent orchestration",
        "Webhooks",
        "Multi-workspaces",
        "Monitoring",
        "Observability",
        "Priority support",
        "Pay-as-you-go AI usage",
      ],
      creditLimit: "5M requests",
      popular: true,
    },
    {
      name: "Enterprise",
      description: "Dedicated infrastructure, SLA, private deployment, AI orchestration, governance, compliance, audit logs, advanced API access.",
      monthlyPrice: null, yearlyPrice: null, originalPrice: null, setupFee: null,
      cta: "Contact the team",
      ctaLink: "/contact",
      gradient: "var(--integration-grad-3)",
      previousPlan: "Scale",
      features: [
        "Dedicated infrastructure",
        "Guaranteed SLA",
        "Private deployment",
        "AI orchestration",
        "Governance",
        "Compliance",
        "Audit logs",
        "Advanced API access",
      ],
      creditLimit: "Unlimited",
      popular: false,
    },
  ],
};

export const DEFAULT_SEO: SeoContent = {
  fr: {
    homepage: {
      title: "MentivisOS - Le système de formation native IA",
      description: "MentivisOS mesure les écarts de compétences, génère des parcours personnalisés et pilote la montée en compétences de vos équipes.",
      jsonLd: {
        "@context": "https://schema.org",
        "@type": "SoftwareApplication",
        name: "MentivisOS",
        applicationCategory: "EducationApplication",
        description: "Système de formation native IA pour entreprises et institutions.",
        url: SITE_URL,
        offers: {
          "@type": "AggregateOffer",
          lowPrice: "990",
          highPrice: "2900",
          priceCurrency: "EUR",
          offerCount: "3",
        },
      },
    },
    tarifs: {
      title: "Tarifs - MentivisOS",
      description: "Des solutions adaptées à chaque étape de votre croissance, de l'apprenant individuel au déploiement enterprise.",
      jsonLd: {
        "@context": "https://schema.org",
        "@type": "Product",
        name: "MentivisOS",
        description: "Système de formation native IA pour entreprises.",
        offers: {
          "@type": "AggregateOffer",
          lowPrice: "990",
          highPrice: "2900",
          priceCurrency: "EUR",
          offerCount: "3",
          availability: "https://schema.org/ContactForAvailability",
        },
      },
    },
    blog: {
      title: "News - MentivisOS",
      description: "Actualités, analyses et points de vue sur la formation et l'IA.",
      jsonLd: {
        "@context": "https://schema.org",
        "@type": "Blog",
        name: "News MentivisOS",
        description: "Actualités et analyses sur la formation et l'IA.",
      },
    },
    business: {
      title: "Mentivis - Coordonnées",
      description: "Adresse, téléphone et localisation de Mentivis, 60 rue François 1er, 75008 Paris.",
      jsonLd: {
        "@context": "https://schema.org",
        "@type": "LocalBusiness",
        name: "Mentivis",
        address: {
          "@type": "PostalAddress",
          streetAddress: "60 rue François 1er",
          postalCode: "75008",
          addressLocality: "Paris",
          addressCountry: "FR",
        },
        telephone: "+33189481002",
        url: SITE_URL,
        hasMap: "https://maps.google.com/?q=60+rue+Fran%C3%A7ois+1er+75008+Paris",
      },
    },
  },
  en: {
    homepage: {
      title: "MentivisOS - The AI-native training system",
      description: "MentivisOS measures skill gaps, generates personalised learning paths and drives your teams' skill development.",
      jsonLd: {
        "@context": "https://schema.org",
        "@type": "SoftwareApplication",
        name: "MentivisOS",
        applicationCategory: "EducationApplication",
        description: "AI-native training system for enterprises and institutions.",
        url: SITE_URL,
        offers: {
          "@type": "AggregateOffer",
          lowPrice: "990",
          highPrice: "2900",
          priceCurrency: "EUR",
          offerCount: "3",
        },
      },
    },
    tarifs: {
      title: "Pricing - MentivisOS",
      description: "Solutions adapted to every stage of your growth, from individual learner to enterprise deployment.",
      jsonLd: {
        "@context": "https://schema.org",
        "@type": "Product",
        name: "MentivisOS",
        description: "AI-native training system for enterprises.",
        offers: {
          "@type": "AggregateOffer",
          lowPrice: "990",
          highPrice: "2900",
          priceCurrency: "EUR",
          offerCount: "3",
          availability: "https://schema.org/ContactForAvailability",
        },
      },
    },
    blog: {
      title: "News - MentivisOS",
      description: "News, insights and perspectives on training and AI.",
      jsonLd: {
        "@context": "https://schema.org",
        "@type": "Blog",
        name: "MentivisOS News",
        description: "News and analysis on training and AI.",
      },
    },
    business: {
      title: "Mentivis - Contact",
      description: "Address, phone and location of Mentivis, 60 rue François 1er, 75008 Paris, France.",
      jsonLd: {
        "@context": "https://schema.org",
        "@type": "LocalBusiness",
        name: "Mentivis",
        address: {
          "@type": "PostalAddress",
          streetAddress: "60 rue François 1er",
          postalCode: "75008",
          addressLocality: "Paris",
          addressCountry: "FR",
        },
        telephone: "+33189481002",
        url: SITE_URL,
        hasMap: "https://maps.google.com/?q=60+rue+Fran%C3%A7ois+1er+75008+Paris",
      },
    },
  },
};
