// Fallback pricing data used when CMS has no data

export const HOVER_GRADIENTS: Record<string, string> = {
  "Starter": "linear-gradient(135deg, #7eb8c8 0%, #a89bc2 50%, #d4b896 100%)",
  "Essentiel": "linear-gradient(135deg, #96c4a8 0%, #7eb8c8 50%, #a89bc2 100%)",
  "Pro": "linear-gradient(135deg, #96c4a8 0%, #7eb8c8 50%, #a89bc2 100%)",
  "Équipe": "linear-gradient(135deg, #d4b896 0%, #96c4a8 50%, #7eb8c8 100%)",
  "Entreprise": "linear-gradient(135deg, #a89bc2 0%, #c49696 50%, #d4b896 100%)",
};

export const FALLBACK_PLANS = {
  learningos: [
    {
      name: "Starter",
      description: "Pour structurer rapidement une académie interne pilotée par IA.",
      monthlyPrice: 990,
      yearlyPrice: 950,
      originalPrice: 990,
      setupFee: 3500,
      cta: "Choisir Starter",
      ctaLink: "https://app.mentivisOS.com",
      gradient: "var(--module-grad-2)",
      previousPlan: null,
      features: [
        "Génération automatique de parcours de formation personnalisés",
        "Adaptation des contenus selon vos métiers et référentiels internes",
        "Agents IA conversationnels pour accompagner les collaborateurs",
        "Suivi des compétences et progression en temps réel",
        "Espace entreprise sécurisé",
        "Déploiement rapide sans équipe pédagogique interne",
        "Compatible financement OPCO",
      ],
      creditLimit: "100 apprenants",
      popular: false,
    },
    {
      name: "Growth",
      description: "Pour industrialiser la montée en compétences à l'échelle d'une équipe ou d'un réseau.",
      monthlyPrice: 2900,
      yearlyPrice: 2700,
      originalPrice: 2900,
      setupFee: 8500,
      cta: "Choisir Growth",
      ctaLink: "/demo",
      gradient: "var(--module-grad-3)",
      previousPlan: "Starter",
      features: [
        "Tout Starter",
        "Génération avancée de parcours certifiants",
        "Adaptation automatique selon les postes, niveaux et objectifs",
        "Bibliothèque métier dynamique alimentée par IA",
        "Tableaux de pilotage RH et compétences",
        "Workflows de validation managériale",
        "Reporting conformité et traçabilité formation",
        "Assistance au montage des financements publics et OPCO",
        "API et intégrations SIRH",
      ],
      creditLimit: "500 utilisateurs",
      popular: true,
    },
    {
      name: "Enterprise",
      description: "Pour construire une véritable infrastructure de formation autonome et certifiante.",
      monthlyPrice: null,
      yearlyPrice: null,
      originalPrice: null,
      setupFee: null,
      setupFeeRange: "Sur devis",
      cta: "Contacter l'équipe",
      ctaLink: "/contact",
      gradient: "var(--module-grad-5)",
      previousPlan: "Growth",
      features: [
        "Académie IA sur mesure",
        "Référentiels métiers personnalisés",
        "Génération continue de contenus et évaluations",
        "Parcours RNCP / Qualiopi compatibles",
        "Architecture multi-sites et multi-entités",
        "Gouvernance des compétences en temps réel",
        "Automatisation des obligations réglementaires",
        "Connecteurs SI, ERP, ATS et SIRH",
        "Hébergement dédié et gouvernance souveraine",
        "Équipe stratégique Mentivis dédiée",
      ],
      creditLimit: "Sur devis",
      popular: false,
    },
  ],
  pipelineos: [
    {
      name: "Starter",
      description: "ATS, pipeline candidats, matching simple, dashboard RH, workflows recrutement, automatisations basiques.",
      monthlyPrice: 1490,
      yearlyPrice: 1400,
      originalPrice: 1490,
      setupFee: 5000,
      cta: "Choisir Starter",
      ctaLink: "https://app.mentivisOS.com",
      gradient: "var(--module-grad-2)",
      previousPlan: null,
      features: [
        "ATS complet",
        "Pipeline candidats",
        "Matching simple",
        "Dashboard RH",
        "Workflows recrutement",
        "Automatisations basiques",
      ],
      creditLimit: "Illimité",
      popular: false,
    },
    {
      name: "Growth",
      description: "IA matching, scoring, multi-recruteurs, portail candidats, automatisations avancées, analytics RH, onboarding sync LearningOS.",
      monthlyPrice: 4900,
      yearlyPrice: 4600,
      originalPrice: 4900,
      setupFee: 12000,
      cta: "Choisir Growth",
      ctaLink: "/demo",
      gradient: "var(--module-grad-3)",
      previousPlan: "Starter",
      features: [
        "IA matching avancé",
        "Scoring candidats",
        "Multi-recruteurs",
        "Portail candidats",
        "Automatisations avancées",
        "Analytics RH",
        "Onboarding sync LearningOS",
      ],
      creditLimit: "Illimité",
      popular: true,
    },
    {
      name: "Enterprise",
      description: "Orchestration recrutement, copilots RH, workflows IA, API RH, intégration SI RH, multi-filiales, gouvernance, architecture dédiée.",
      monthlyPrice: null,
      yearlyPrice: 75000,
      originalPrice: null,
      setupFee: null,
      setupFeeRange: "20 000€ - 120 000€",
      cta: "Contacter l'équipe",
      ctaLink: "/contact",
      gradient: "var(--module-grad-5)",
      previousPlan: "Growth",
      features: [
        "Orchestration recrutement",
        "Copilots RH",
        "Workflows IA",
        "API RH complète",
        "Intégration SI RH",
        "Multi-filiales",
        "Gouvernance",
        "Architecture dédiée",
      ],
      creditLimit: "Illimité",
      popular: false,
    },
  ],
  api: [
    {
      name: "Build",
      description: "500k requêtes, auth, workflows, embeddings, analytics basiques, rate limiting. Usage IA en supplément.",
      monthlyPrice: 990,
      yearlyPrice: 950,
      originalPrice: 990,
      setupFee: 0,
      cta: "Commencer",
      ctaLink: "https://app.mentivisOS.com",
      gradient: "var(--integration-grad-1)",
      previousPlan: null,
      features: [
        "500k requêtes/mois",
        "Authentification",
        "Workflows",
        "Embeddings",
        "Analytics basiques",
        "Rate limiting",
        "Usage IA payant",
      ],
      creditLimit: "500k requêtes",
      popular: false,
    },
    {
      name: "Scale",
      description: "5M requêtes, orchestration agents, webhooks, multi-workspaces, monitoring, observabilité, support prioritaire. Usage IA en supplément.",
      monthlyPrice: 3900,
      yearlyPrice: 3700,
      originalPrice: 3900,
      setupFee: 0,
      cta: "Choisir Scale",
      ctaLink: "https://app.mentivisOS.com",
      gradient: "var(--integration-grad-2)",
      previousPlan: "Build",
      features: [
        "5M requêtes/mois",
        "Orchestration agents",
        "Webhooks",
        "Multi-workspaces",
        "Monitoring",
        "Observabilité",
        "Support prioritaire",
        "Usage IA payant",
      ],
      creditLimit: "5M requêtes",
      popular: true,
    },
    {
      name: "Enterprise",
      description: "Infrastructure dédiée, SLA, private deployment, orchestration IA, gouvernance, conformité, audit logs, accès avancé API.",
      monthlyPrice: null,
      yearlyPrice: 95000,
      originalPrice: null,
      setupFee: null,
      setupFeeRange: "Sur devis",
      cta: "Contacter l'équipe",
      ctaLink: "/contact",
      gradient: "var(--integration-grad-3)",
      previousPlan: "Scale",
      features: [
        "Infrastructure dédiée",
        "SLA garanti",
        "Private deployment",
        "Orchestration IA",
        "Gouvernance",
        "Conformité",
        "Audit logs",
        "Accès avancé API",
      ],
      creditLimit: "Illimité",
      popular: false,
    },
  ],
};

export const FEATURES_COMPARISON = {
  learningos: [
    { name: "Apprenants", starter: "1", essentiel: "10", equipe: "50", entreprise: "Illimité" },
    { name: "Diagnostics IA", starter: "Illimité", essentiel: "Illimité", equipe: "Illimité", entreprise: "Illimité" },
    { name: "Programmes personnalisés", starter: "Illimité", essentiel: "Illimité", equipe: "Illimité", entreprise: "Illimité" },
    { name: "Assistant pédagogique", starter: "Avancé", essentiel: "Avancé", equipe: "Avancé", entreprise: "Avancé" },
    { name: "Tableau de bord manager", starter: "—", essentiel: "✓", equipe: "✓", entreprise: "✓" },
    { name: "Intégration SIRH", starter: "—", essentiel: "—", equipe: "✓", entreprise: "✓" },
    { name: "API", starter: "—", essentiel: "—", equipe: "—", entreprise: "✓" },
    { name: "Marque blanche", starter: "—", essentiel: "—", equipe: "—", entreprise: "✓" },
    { name: "Support", starter: "Email", essentiel: "Prioritaire", equipe: "Prioritaire", entreprise: "CSM dédié" },
  ],
  pipelineos: [
    { name: "Offres d'emploi", gratuit: "3", starter: "10", pro: "Illimité", entreprise: "Illimité" },
    { name: "Candidatures/mois", gratuit: "10", starter: "100", pro: "500", entreprise: "Illimité" },
    { name: "Analyse IA", gratuit: "Base", starter: "Avancée", pro: "Avancée", entreprise: "Avancée" },
    { name: "Score de matching", gratuit: "✓", starter: "✓", pro: "✓", entreprise: "✓" },
    { name: "Tests techniques", gratuit: "—", starter: "✓", pro: "✓", entreprise: "✓" },
    { name: "Intégration ATS", gratuit: "—", starter: "—", pro: "✓", entreprise: "✓" },
    { name: "API Pipeline", gratuit: "—", starter: "—", pro: "—", entreprise: "✓" },
    { name: "Support", gratuit: "Email", starter: "Email", pro: "Prioritaire", entreprise: "Dédié" },
  ],
  api: [
    { name: "Requêtes/mois", starter: "10 000", pro: "100 000", entreprise: "Illimité" },
    { name: "Diagnostic API", starter: "✓", pro: "✓", entreprise: "✓" },
    { name: "Programme API", starter: "✓", pro: "✓", entreprise: "✓" },
    { name: "Webhooks", starter: "—", pro: "✓", entreprise: "✓" },
    { name: "Rate limit", starter: "Standard", pro: "Élevé", entreprise: "Personnalisé" },
    { name: "SLA", starter: "—", pro: "99,9%", entreprise: "99,99%" },
    { name: "Support", starter: "Technique", pro: "Prioritaire", entreprise: "24/7" },
  ],
};

export const FAQ_ITEMS = [
  {
    question: "Comment fonctionne la facturation ?",
    answer: "La facturation s'effectue mensuellement ou annuellement selon votre choix. Le paiement est sécurisé par prélèvement automatique. Vous pouvez changer de plan ou annuler à tout moment.",
  },
  {
    question: "Puis-je changer de plan en cours d'abonnement ?",
    answer: "Oui, vous pouvez upgrader ou downgrader votre plan à tout moment. Lors d'un upgrade, vous êtes facturés au prorata. Lors d'un downgrade, le changement prend effet à la fin du cycle de facturation.",
  },
  {
    question: "Y a-t-il une période d'essai ?",
    answer: "Oui, tous nos plans payants incluent une période d'essai de 14 jours. Vous disposez de toutes les fonctionnalités du plan choisi pendant cette période, sans engagement.",
  },
  {
    question: "Que se passe-t-il après la période d'essai ?",
    answer: "À la fin des 14 jours, votre abonnement devient actif automatiquement avec le moyen de paiement enregistré. Vous pouvez annuler à tout moment avant la fin de l'essai sans frais.",
  },
  {
    question: "Proposez-vous des tarifs pour les PME ?",
    answer: "Oui ! Notre programme petite PME offre 3 mois d'accès gratuit au plan Équipe pour les entreprises de moins de 50 salariés. Contactez-nous pour postuler.",
  },
  {
    question: "Comment fonctionne le programme petite PME ?",
    answer: "Les PME de moins de 50 salariés peuvent bénéficier de 3 mois gratuits au plan Équipe. Postulez via notre formulaire dédié et notre équipe examinera votre dossier sous 48h.",
  },
];
