import { PricingPlan } from "@/lib/cms/types";

// Fallback pricing data used when CMS has no data

export const HOVER_GRADIENTS: Record<string, string> = {
  "Open MentivisOS": "linear-gradient(135deg, #7eb8c8 0%, #a89bc2 50%, #d4b896 100%)",
  "Entreprise Démo": "linear-gradient(135deg, #96c4a8 0%, #7eb8c8 50%, #a89bc2 100%)",
  "Enterprise Demo": "linear-gradient(135deg, #96c4a8 0%, #7eb8c8 50%, #a89bc2 100%)",
  "Starter": "linear-gradient(135deg, #7eb8c8 0%, #a89bc2 50%, #d4b896 100%)",
  "Growth": "linear-gradient(135deg, #96c4a8 0%, #7eb8c8 50%, #a89bc2 100%)",
  "Enterprise": "linear-gradient(135deg, #a89bc2 0%, #c49696 50%, #d4b896 100%)",
  "Build": "linear-gradient(135deg, #7eb8c8 0%, #a89bc2 50%, #d4b896 100%)",
  "Scale": "linear-gradient(135deg, #96c4a8 0%, #7eb8c8 50%, #a89bc2 100%)",
};

export const FALLBACK_PLANS = {
  learningos: [
    {
      name: "Open MentivisOS",
      description: "Avec Open MentivisOS, un accès libre au savoir. Gratuit pour toujours, apprenez ce que vous voulez, quand vous voulez",
      monthlyPrice: 0,
      yearlyPrice: 0,
      originalPrice: 990,
      setupFee: 0,
      cta: "Free pour toujours !",
      ctaLink: "https://open.mentivisOS.com",
      gradient: "var(--module-grad-2)",
      previousPlan: null,
      features: [
        "Génération automatique de parcours de formation personnalisés",
        "Adaptation des contenus selon vos métiers et référentiels internes",
        "Agents IA conversationnels pour accompagner les collaborateurs",
        "Suivi des compétences et progression en temps réel",
        "4 cursus maximum",
        "Apprenez tous les sujets",
        "Idéal également pour étudiants",
      ],
      creditLimit: "Une personne",
      popular: true,
    },
    {
      name: "Entreprise Démo",
      description: "Pour industrialiser la montée en compétences à l'échelle d'une équipe ou d'un réseau.",
      monthlyPrice: 0,
      yearlyPrice: 0,
      originalPrice: 2900,
      setupFee: 0,
      cta: "Testez avec vos programmes !",
      ctaLink: "https://demo.mentivisos.com",
      gradient: "var(--module-grad-3)",
      previousPlan: "Starter",
      features: [
        "Tout Open MentivisOS",
        "Génération avancée de parcours certifiants",
        "Adaptation automatique selon les postes, niveaux et objectifs",
        "Bibliothèque métier dynamique alimentée par IA",
        "Tableaux de pilotage RH et compétences",
        "Workflows de validation managériale",
        "Reporting conformité et traçabilité formation",
        "Assistance au montage des financements publics et OPCO",
        "API et intégrations SIRH",
      ],
      creditLimit: "500 utilisateurs",
      popular: false,
    },
    {
      name: "Enterprise",
      description: "Pour construire une véritable infrastructure de formation autonome et certifiante.",
      monthlyPrice: null,
      yearlyPrice: null,
      originalPrice: null,
      setupFee: 15000,
      cta: "Contacter l'équipe",
      ctaLink: "/contact",
      gradient: "var(--module-grad-4)",
      previousPlan: "Growth",
      features: [
        "Tout Growth",
        "Générateur de certifications et référentiels internes",
        "Modèle pédagogique propriétaire adapté à vos métiers",
        "Ingénierie pédagogique dédiée et accompagnement continu",
        "Intégrations avancées SIRH, LMS, CRM",
        "Déploiement multi-sites et multi-pays",
        "SLA garanti et support prioritaire",
        "Conformité RGPD, ISO 27001, accessibilité",
        "Audit Qualiopi et accompagnement certification",
      ],
      creditLimit: "Illimité",
      popular: false,
    },
  ],
  pipelineos: [
    {
      name: "Starter",
      description: "ATS, pipeline candidats, matching simple, dashboard RH, workflows recrutement, automatisations basiques.",
      monthlyPrice: 1490,
      yearlyPrice: 1400,
      originalPrice: 1490,
      setupFee: 5000,
      cta: "Choisir Starter",
      ctaLink: "https://app.mentivisOS.com",
      gradient: "var(--module-grad-2)",
      previousPlan: null,
      features: [
        "ATS complet",
        "Pipeline candidats",
        "Matching simple",
        "Dashboard RH",
        "Workflows recrutement",
        "Automatisations basiques",
      ],
      creditLimit: "Illimité",
      popular: false,
    },
    {
      name: "Growth",
      description: "IA matching, scoring, multi-recruteurs, portail candidats, automatisations avancées, analytics RH, onboarding sync MentivisOS Pro.",
      monthlyPrice: 4900,
      yearlyPrice: 4600,
      originalPrice: 4900,
      setupFee: 12000,
      cta: "Choisir Growth",
      ctaLink: "/demo",
      gradient: "var(--module-grad-3)",
      previousPlan: "Starter",
      features: [
        "IA matching avancé",
        "Scoring candidats",
        "Multi-recruteurs",
        "Portail candidats",
        "Automatisations avancées",
        "Analytics RH",
        "Onboarding sync MentivisOS Pro",
      ],
      creditLimit: "Illimité",
      popular: true,
    },
    {
      name: "Enterprise",
      description: "Orchestration recrutement, copilots RH, workflows IA, API RH, intégration SI RH, multi-filiales, gouvernance, architecture dédiée.",
      monthlyPrice: null,
      yearlyPrice: 75000,
      originalPrice: null,
      setupFee: null,
      setupFeeRange: "20 000€ - 120 000€",
      cta: "Contacter l'équipe",
      ctaLink: "/contact",
      gradient: "var(--module-grad-5)",
      previousPlan: "Growth",
      features: [
        "Orchestration recrutement",
        "Copilots RH",
        "Workflows IA",
        "API RH complète",
        "Intégration SI RH",
        "Multi-filiales",
        "Gouvernance",
        "Architecture dédiée",
      ],
      creditLimit: "Illimité",
      popular: false,
    },
  ],
  api: [
    {
      name: "Build",
      description: "500k requêtes, auth, workflows, embeddings, analytics basiques, rate limiting. Usage IA en supplément.",
      monthlyPrice: 990,
      yearlyPrice: 950,
      originalPrice: 990,
      setupFee: 0,
      cta: "Commencer",
      ctaLink: "https://app.mentivisOS.com",
      gradient: "var(--integration-grad-1)",
      previousPlan: null,
      features: [
        "500k requêtes/mois",
        "Authentification",
        "Workflows",
        "Embeddings",
        "Analytics basiques",
        "Rate limiting",
        "Usage IA payant",
      ],
      creditLimit: "500k requêtes",
      popular: false,
    },
    {
      name: "Scale",
      description: "5M requêtes, orchestration agents, webhooks, multi-workspaces, monitoring, observabilité, support prioritaire. Usage IA en supplément.",
      monthlyPrice: 3900,
      yearlyPrice: 3700,
      originalPrice: 3900,
      setupFee: 0,
      cta: "Choisir Scale",
      ctaLink: "https://app.mentivisOS.com",
      gradient: "var(--integration-grad-2)",
      previousPlan: "Build",
      features: [
        "5M requêtes/mois",
        "Orchestration agents",
        "Webhooks",
        "Multi-workspaces",
        "Monitoring",
        "Observabilité",
        "Support prioritaire",
        "Usage IA payant",
      ],
      creditLimit: "5M requêtes",
      popular: true,
    },
    {
      name: "Enterprise",
      description: "Infrastructure dédiée, SLA, private deployment, orchestration IA, gouvernance, conformité, audit logs, accès avancé API.",
      monthlyPrice: null,
      yearlyPrice: 95000,
      originalPrice: null,
      setupFee: null,
      setupFeeRange: "Sur devis",
      cta: "Contacter l'équipe",
      ctaLink: "/contact",
      gradient: "var(--integration-grad-3)",
      previousPlan: "Scale",
      features: [
        "Infrastructure dédiée",
        "SLA garanti",
        "Private deployment",
        "Orchestration IA",
        "Gouvernance",
        "Conformité",
        "Audit logs",
        "Accès avancé API",
      ],
      creditLimit: "Illimité",
      popular: false,
    },
  ],
};

export const FALLBACK_PLANS_EN: Record<string, PricingPlan[]> = {
  learningos: [
    {
      name: "Open MentivisOS",
      description: "Free access to knowledge. Learn what you want, when you want, forever.",
      monthlyPrice: 0, yearlyPrice: 0, originalPrice: 990, setupFee: 0,
      cta: "Free forever!",
      ctaLink: "https://open.mentivisOS.com",
      gradient: "var(--module-grad-2)",
      previousPlan: null,
      features: [
        "Auto-generated personalized training paths",
        "Content adaptation based on your roles and frameworks",
        "Conversational AI agents for employee support",
        "Real-time skills and progress tracking",
        "Up to 4 courses",
        "Learn any subject",
        "Ideal for students as well",
      ],
      creditLimit: "One person",
      popular: true,
    },
    {
      name: "Enterprise Demo",
      description: "Scale up skills training across your team or network.",
      monthlyPrice: 0, yearlyPrice: 0, originalPrice: 2900, setupFee: 0,
      cta: "Test with your programs!",
      ctaLink: "https://demo.mentivisos.com",
      gradient: "var(--module-grad-3)",
      previousPlan: "Starter",
      features: [
        "All Open MentivisOS features",
        "Advanced certified program generation",
        "Automatic adaptation by role, level and objective",
        "AI-powered dynamic business library",
        "HR and skills dashboards",
        "Managerial validation workflows",
        "Compliance reporting and training traceability",
        "Public funding and OPCO application assistance",
        "API and HRIS integrations",
      ],
      creditLimit: "500 users",
      popular: false,
    },
    {
      name: "Enterprise",
      description: "Build a truly autonomous and certifying training infrastructure.",
      monthlyPrice: null, yearlyPrice: null, originalPrice: null, setupFee: 15000,
      cta: "Contact the team",
      ctaLink: "/contact",
      gradient: "var(--module-grad-4)",
      previousPlan: "Growth",
      features: [
        "All Growth features",
        "Certification and internal framework generator",
        "Proprietary pedagogical model adapted to your roles",
        "Dedicated pedagogical engineering and ongoing support",
        "Advanced HRIS, LMS, CRM integrations",
        "Multi-site and multi-country deployment",
        "Guaranteed SLA and priority support",
        "GDPR, ISO 27001, accessibility compliance",
        "Qualiopi audit and certification support",
      ],
      creditLimit: "Unlimited",
      popular: false,
    },
  ],
  pipelineos: [
    {
      name: "Starter",
      description: "ATS, candidate pipeline, basic matching, HR dashboard, recruitment workflows, basic automations.",
      monthlyPrice: null, yearlyPrice: null, originalPrice: 1490, setupFee: null,
      cta: "Choose Starter",
      ctaLink: "https://app.mentivisOS.com",
      gradient: "var(--module-grad-2)",
      previousPlan: null,
      features: [
        "Complete ATS",
        "Candidate pipeline",
        "Basic matching",
        "HR dashboard",
        "Recruitment workflows",
        "Basic automations",
      ],
      creditLimit: "Unlimited",
      popular: false,
    },
    {
      name: "Growth",
      description: "AI matching, scoring, multi-recruiter, candidate portal, advanced automations, HR analytics, MentivisOS Pro onboarding sync.",
      monthlyPrice: null, yearlyPrice: null, originalPrice: 4900, setupFee: null,
      cta: "Choose Growth",
      ctaLink: "/demo",
      gradient: "var(--module-grad-3)",
      previousPlan: "Starter",
      features: [
        "Advanced AI matching",
        "Candidate scoring",
        "Multi-recruiter",
        "Candidate portal",
        "Advanced automations",
        "HR analytics",
        "MentivisOS Pro onboarding sync",
      ],
      creditLimit: "Unlimited",
      popular: true,
    },
    {
      name: "Enterprise",
      description: "Recruitment orchestration, HR copilots, AI workflows, complete HR API, HRIS integration, multi-subsidiary, governance, dedicated architecture.",
      monthlyPrice: null, yearlyPrice: null, originalPrice: null, setupFee: null,
      cta: "Contact the team",
      ctaLink: "/contact",
      gradient: "var(--module-grad-5)",
      previousPlan: "Growth",
      features: [
        "Recruitment orchestration",
        "HR copilots",
        "AI workflows",
        "Complete HR API",
        "HRIS integration",
        "Multi-subsidiary",
        "Governance",
        "Dedicated architecture",
      ],
      creditLimit: "Unlimited",
      popular: false,
    },
  ],
  api: [
    {
      name: "Build",
      description: "500k requests, auth, workflows, embeddings, basic analytics, rate limiting. AI usage billed separately.",
      monthlyPrice: null, yearlyPrice: null, originalPrice: 990, setupFee: null,
      cta: "Get started",
      ctaLink: "https://app.mentivisOS.com",
      gradient: "var(--integration-grad-1)",
      previousPlan: null,
      features: [
        "500k requests/month",
        "Authentication",
        "Workflows",
        "Embeddings",
        "Basic analytics",
        "Rate limiting",
        "Pay-as-you-go AI usage",
      ],
      creditLimit: "500k requests",
      popular: false,
    },
    {
      name: "Scale",
      description: "5M requests, agent orchestration, webhooks, multi-workspaces, monitoring, observability, priority support. AI usage billed separately.",
      monthlyPrice: null, yearlyPrice: null, originalPrice: 3900, setupFee: null,
      cta: "Choose Scale",
      ctaLink: "https://app.mentivisOS.com",
      gradient: "var(--integration-grad-2)",
      previousPlan: "Build",
      features: [
        "5M requests/month",
        "Agent orchestration",
        "Webhooks",
        "Multi-workspaces",
        "Monitoring",
        "Observability",
        "Priority support",
        "Pay-as-you-go AI usage",
      ],
      creditLimit: "5M requests",
      popular: true,
    },
    {
      name: "Enterprise",
      description: "Dedicated infrastructure, SLA, private deployment, AI orchestration, governance, compliance, audit logs, advanced API access.",
      monthlyPrice: null, yearlyPrice: null, originalPrice: null, setupFee: null,
      cta: "Contact the team",
      ctaLink: "/contact",
      gradient: "var(--integration-grad-3)",
      previousPlan: "Scale",
      features: [
        "Dedicated infrastructure",
        "Guaranteed SLA",
        "Private deployment",
        "AI orchestration",
        "Governance",
        "Compliance",
        "Audit logs",
        "Advanced API access",
      ],
      creditLimit: "Unlimited",
      popular: false,
    },
  ],
};

export const FEATURES_COMPARISON = {
  learningos: [
    { name: "Apprenants", starter: "1", essentiel: "10", equipe: "50", entreprise: "Illimité" },
    { name: "Diagnostics IA", starter: "Illimité", essentiel: "Illimité", equipe: "Illimité", entreprise: "Illimité" },
    { name: "Programmes personnalisés", starter: "Illimité", essentiel: "Illimité", equipe: "Illimité", entreprise: "Illimité" },
    { name: "Assistant pédagogique", starter: "Avancé", essentiel: "Avancé", equipe: "Avancé", entreprise: "Avancé" },
    { name: "Tableau de bord manager", starter: "—", essentiel: "✓", equipe: "✓", entreprise: "✓" },
    { name: "Intégration SIRH", starter: "—", essentiel: "—", equipe: "✓", entreprise: "✓" },
    { name: "API", starter: "—", essentiel: "—", equipe: "—", entreprise: "✓" },
    { name: "Marque blanche", starter: "—", essentiel: "—", equipe: "—", entreprise: "✓" },
    { name: "Support", starter: "Email", essentiel: "Prioritaire", equipe: "Prioritaire", entreprise: "CSM dédié" },
  ],
  pipelineos: [
    { name: "Offres d'emploi", gratuit: "3", starter: "10", pro: "Illimité", entreprise: "Illimité" },
    { name: "Candidatures/mois", gratuit: "10", starter: "100", pro: "500", entreprise: "Illimité" },
    { name: "Analyse IA", gratuit: "Base", starter: "Avancée", pro: "Avancée", entreprise: "Avancée" },
    { name: "Score de matching", gratuit: "✓", starter: "✓", pro: "✓", entreprise: "✓" },
    { name: "Tests techniques", gratuit: "—", starter: "✓", pro: "✓", entreprise: "✓" },
    { name: "Intégration ATS", gratuit: "—", starter: "—", pro: "✓", entreprise: "✓" },
    { name: "API Pipeline", gratuit: "—", starter: "—", pro: "—", entreprise: "✓" },
    { name: "Support", gratuit: "Email", starter: "Email", pro: "Prioritaire", entreprise: "Dédié" },
  ],
  api: [
    { name: "Requêtes/mois", starter: "10 000", pro: "100 000", entreprise: "Illimité" },
    { name: "Diagnostic API", starter: "✓", pro: "✓", entreprise: "✓" },
    { name: "Programme API", starter: "✓", pro: "✓", entreprise: "✓" },
    { name: "Webhooks", starter: "—", pro: "✓", entreprise: "✓" },
    { name: "Rate limit", starter: "Standard", pro: "Élevé", entreprise: "Personnalisé" },
    { name: "SLA", starter: "—", pro: "99,9%", entreprise: "99,99%" },
    { name: "Support", starter: "Technique", pro: "Prioritaire", entreprise: "24/7" },
  ],
};

export const FAQ_ITEMS = [
  {
    question: "Comment fonctionne la facturation ?",
    answer: "La facturation s'effectue mensuellement ou annuellement selon votre choix. Le paiement est sécurisé par prélèvement automatique. Vous pouvez changer de plan ou annuler à tout moment.",
  },
  {
    question: "Puis-je changer de plan en cours d'abonnement ?",
    answer: "Oui, vous pouvez upgrader ou downgrader votre plan à tout moment. Lors d'un upgrade, vous êtes facturés au prorata. Lors d'un downgrade, le changement prend effet à la fin du cycle de facturation.",
  },
  {
    question: "Y a-t-il une période d'essai ?",
    answer: "Oui, tous nos plans payants incluent une période d'essai de 14 jours. Vous disposez de toutes les fonctionnalités du plan choisi pendant cette période, sans engagement.",
  },
  {
    question: "Que se passe-t-il après la période d'essai ?",
    answer: "À la fin des 14 jours, votre abonnement devient actif automatiquement avec le moyen de paiement enregistré. Vous pouvez annuler à tout moment avant la fin de l'essai sans frais.",
  },
  {
    question: "Proposez-vous des tarifs pour les PME ?",
    answer: "Oui ! Notre programme petite PME offre 3 mois d'accès gratuit au plan Équipe pour les entreprises de moins de 50 salariés. Contactez-nous pour postuler.",
  },
  {
    question: "Comment fonctionne le programme petite PME ?",
    answer: "Les PME de moins de 50 salariés peuvent bénéficier de 3 mois gratuits au plan Équipe. Postulez via notre formulaire dédié et notre équipe examinera votre dossier sous 48h.",
  },
];

export const FEATURES_COMPARISON_EN = {
  learningos: [
    { name: "Learners", starter: "1", growth: "10", enterprise: "50", enterprisePlus: "Unlimited" },
    { name: "AI Diagnostics", starter: "Unlimited", growth: "Unlimited", enterprise: "Unlimited", enterprisePlus: "Unlimited" },
    { name: "Custom Programs", starter: "Unlimited", growth: "Unlimited", enterprise: "Unlimited", enterprisePlus: "Unlimited" },
    { name: "AI Teaching Assistant", starter: "Advanced", growth: "Advanced", enterprise: "Advanced", enterprisePlus: "Advanced" },
    { name: "Manager Dashboard", starter: "—", growth: "✓", enterprise: "✓", enterprisePlus: "✓" },
    { name: "HRIS Integration", starter: "—", growth: "—", enterprise: "✓", enterprisePlus: "✓" },
    { name: "API", starter: "—", growth: "—", enterprise: "—", enterprisePlus: "✓" },
    { name: "White Label", starter: "—", growth: "—", enterprise: "—", enterprisePlus: "✓" },
    { name: "Support", starter: "Email", growth: "Priority", enterprise: "Priority", enterprisePlus: "Dedicated CSM" },
  ],
  pipelineos: [
    { name: "Job Listings", free: "3", starter: "10", pro: "Unlimited", enterprise: "Unlimited" },
    { name: "Applications/month", free: "10", starter: "100", pro: "500", enterprise: "Unlimited" },
    { name: "AI Analysis", free: "Basic", starter: "Advanced", pro: "Advanced", enterprise: "Advanced" },
    { name: "Matching Score", free: "✓", starter: "✓", pro: "✓", enterprise: "✓" },
    { name: "Technical Tests", free: "—", starter: "✓", pro: "✓", enterprise: "✓" },
    { name: "ATS Integration", free: "—", starter: "—", pro: "✓", enterprise: "✓" },
    { name: "API Pipeline", free: "—", starter: "—", pro: "—", enterprise: "✓" },
    { name: "Support", free: "Email", starter: "Email", pro: "Priority", enterprise: "Dedicated" },
  ],
  api: [
    { name: "Requests/month", build: "10,000", scale: "100,000", enterprise: "Unlimited" },
    { name: "API Diagnostics", build: "✓", scale: "✓", enterprise: "✓" },
    { name: "API Programs", build: "✓", scale: "✓", enterprise: "✓" },
    { name: "Webhooks", build: "—", scale: "✓", enterprise: "✓" },
    { name: "Rate Limit", build: "Standard", scale: "High", enterprise: "Custom" },
    { name: "SLA", build: "—", scale: "99.9%", enterprise: "99.99%" },
    { name: "Support", build: "Technical", scale: "Priority", enterprise: "24/7" },
  ],
};

export const FAQ_ITEMS_EN = [
  {
    question: "How does billing work?",
    answer: "Billing is monthly or annual based on your choice. Payment is secured via automatic debit. You can change your plan or cancel at any time.",
  },
  {
    question: "Can I change my plan mid-subscription?",
    answer: "Yes, you can upgrade or downgrade your plan at any time. Upgrades are prorated. Downgrades take effect at the end of your billing cycle.",
  },
  {
    question: "Is there a trial period?",
    answer: "Yes, all paid plans include a 14-day free trial. You get full access to all features of your chosen plan during this period, with no commitment.",
  },
  {
    question: "What happens after the trial?",
    answer: "After 14 days, your subscription activates automatically with your registered payment method. You can cancel anytime before the trial ends at no charge.",
  },
  {
    question: "Do you offer pricing for SMBs?",
    answer: "Yes! Our SMB program offers 3 months of free access to the Growth plan for companies with fewer than 50 employees. Contact us to apply.",
  },
  {
    question: "How does the SMB program work?",
    answer: "SMBs with fewer than 50 employees can receive 3 free months on the Growth plan. Apply via our dedicated form and our team will review your application within 48 hours.",
  },
];
